### ISSUE TITLE
Undertale MIDIs

### ISSUE THREAD

**Issue by juicyjayx** [BearlyWorkingYT/Music#1]
This isn't much of an issue, but I don't know how else to contact you.
Are you able to share the AI continued MIDIs in the Undertale Video? You haven't uploaded them here.
Thanks.

**Comment by DiegoBear** [comment]
Hello, unfortunately, I didn't remember to save the .midis from the Undertale generation. I am sorry, :(

I uploaded what I could find. I will try to do better in the future.

**Comment by BearlyWorkingYT** [comment]
Hello, unfortunately, I didn't remember to save the .midis from the Undertale generation. I am sorry, :(

I uploaded what I could find. I will try to do better in the future.
